import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { FeedPostType } from '@prisma/client';

@Injectable()
export class FeedService {
  constructor(private prisma: PrismaService) {}

  async getFeed(params: {
    page?: number;
    limit?: number;
    type?: FeedPostType;
    blockId?: string;
    provinceId?: string;
    tags?: string[];
  }) {
    const { page = 1, limit = 20, type, blockId, provinceId, tags } = params;
    const skip = (page - 1) * limit;

    const where: any = {};
    if (type) where.type = type;
    if (blockId) where.blockId = blockId;
    if (provinceId) where.provinceId = provinceId;
    if (tags && tags.length > 0) {
      where.tags = { hasSome: tags };
    }

    const [data, total] = await Promise.all([
      this.prisma.feedPost.findMany({
        where,
        skip,
        take: limit,
        include: {
          sourceRef: { select: { url: true, fetchedAt: true } },
          bill: {
            select: { id: true, title: true, externalId: true, status: true },
          },
          voteEvent: {
            select: { id: true, title: true, result: true, affirmative: true, negative: true, abstention: true },
          },
          _count: { select: { comments: true, reactions: true } },
        },
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.feedPost.count({ where }),
    ]);

    return {
      data,
      meta: { total, page, limit, totalPages: Math.ceil(total / limit) },
    };
  }

  async findOne(id: string) {
    return this.prisma.feedPost.findUnique({
      where: { id },
      include: {
        sourceRef: true,
        bill: {
          include: {
            authors: {
              include: {
                legislator: { select: { id: true, fullName: true, photoUrl: true } },
              },
            },
          },
        },
        voteEvent: {
          include: {
            results: {
              include: {
                legislator: { select: { id: true, fullName: true } },
              },
              take: 50,
            },
          },
        },
        _count: { select: { comments: true, reactions: true } },
      },
    });
  }

  async createAutoPost(data: {
    type: FeedPostType;
    title: string;
    body: string;
    payload?: any;
    entityType?: string;
    entityId?: string;
    billId?: string;
    voteEventId?: string;
    blockId?: string;
    provinceId?: string;
    tags?: string[];
    sourceRefId?: string;
  }) {
    return this.prisma.feedPost.create({
      data: {
        ...data,
        isAutoGenerated: true,
      },
    });
  }
}
